### ISSUE TITLE
Peer2Peer_CodeReview 5th Nov 2021

### ISSUE THREAD

**Issue by TheLuisAbarca** [williamrolando88/personal-portfolio#13]
Good job so far @williamrolando88! Nevertheless there a little things to have in mind.

- Is really good that you have a good idea of how to structure a page using the adequate html tags for each part of the page.

- Although is a good thing that the majority of your code in the css file is good structured as well your index file, It would be a great idea that you, position all the changes of default behaviours for native tags in the begging of the file or each section of media queries.
For example:
https://github.com/williamrolando88/personal-portfolio/blob/6b956d72be79189fccf53419ef4e6d25d2dffb85/style.css#L135-L150
In that part you may change that id behaviour at the last part of the changes to default ones.

**Comment by CRClothier** [comment]
Hi William,

Great work so far!  You have done a great job implementing previous advice given to you.

One thing you could look at. I understand why you have left the a tags open below, but is it necessary for the I tag to also be open?  Perhaps this is intentional and maybe it is not a problem :)

https://github.com/williamrolando88/personal-portfolio/blob/6b956d72be79189fccf53419ef4e6d25d2dffb85/index.html#L49-L55
